### ISSUE TITLE
Error parsing the graphql.schema

### ISSUE THREAD

**Issue by riginding** [notarize/qlc#16]
I wanted to try `qlc` out and ran into a problem.

I generated a schema.json file using a script `introspection.js` from the linked blog post, which looks like this:

``` javascript
const fetch = require("node-fetch");
const { introspectionQuery } = require("graphql");
const fs = require("fs");

fetch("https://1jzxrj179.lp.gql.zone/graphql", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ query: introspectionQuery })
})
  .then(res => res.json())
  .then(res =>
    fs.writeFileSync("schema.json", JSON.stringify(res.data, null, 2))
  );
```

After running `qlc -s ./schema.json` I get the following Error Message:
`thread 'main' panicked at 'Failed to parse schema: SchemaJSONParseError(JSONParseError(Error("missing field `data`", line: 22425, column: 1)))', src/libcore/result.rs:999:5
`

It seems to be an error while parsing the json into a serde struct.
What should the content of the missing field `data` look like?

**Comment by dairyisscary** [comment]
@riginding hiya! 👋 

your code looks fine to me, but i think it its just missing the root `.data` object (`.data` here is part of the graph response itself)

```js
fs.writeFileSync("schema.json", JSON.stringify(res, null, 2))
```

**Comment by dairyisscary** [comment]
i think i might stick this example downloader script into the docs somewhere...

**Comment by dairyisscary** [comment]
@riginding did you get this to work? curious if i can close this issue.

**Comment by riginding** [comment]
sorry for the late reply! yes, it worked. :+1: 
I got some `GraphqlFileParseErrors` now. I'm still investigating, I'll might create a new issue if I can't figure it out.
